### ISSUE TITLE
Support client certificate for mtls?

### ISSUE THREAD

**Issue by david-driscoll** [pulumiverse/pulumi-purrl#32]
Would it be possible to add support for sending a client certificate (pem?) with the create or delete request?

**Comment by dirien** [comment]
Hi @david-driscoll,

thanks for your feedback! Yes sounds like a great idea! Let me schedule this.

I also thought about an insecure flag for calling endpoints with a self-signed cert!

**Comment by dirien** [comment]
Hi @david-driscoll,

I created now support for client certificates (v0.3.0)

You have now these new properties for Create and Delete:

```go
CaCert, Cert, Key            
```
You need to set `CaCert` only, when your server cert is not from a trusted public CA.

Let me know if it works for you.
